In [1]:
import main as m

# max and min possible deck sizes for the corporation player
deck_sizes = [40, 44, 45, 49, 50, 54]

# maximum number of 1 2 and 3 point agendas that can be included based on current card pool and banned list (April 21)
max_ones = 15
max_twos = 36
max_threes = 12

df = m.main(deck_sizes, max_ones, max_twos, max_threes)

In [2]:
df.head(50)

,agenda_type,deck_size,agenda_points,agenda_counts,num_agendas,average_accesses
0,Normal,40,18,"[0, 2, 14]",16,15
1,Normal,40,18,"[0, 3, 12]",15,15
2,Normal,40,18,"[0, 4, 10]",14,15
3,Normal,40,18,"[0, 5, 8]",13,15
4,Normal,40,18,"[0, 6, 6]",12,15
5,Normal,40,18,"[0, 7, 4]",11,15
6,Normal,40,18,"[0, 8, 2]",10,15
7,Normal,40,18,"[0, 9, 0]",9,16
8,Normal,40,18,"[1, 0, 15]",16,15
9,Normal,40,18,"[1, 1, 13]",15,15
10,Normal,40,18,"[1, 2, 11]",14,15
11,Normal,40,18,"[1, 3, 9]",13,15
12,Normal,40,18,"[1, 4, 7]",12,15
13,Normal,40,18,"[1, 5, 5]",11,15
14,Normal,40,18,"[1, 6, 3]",10,15
15,Normal,40,18,"[1, 7, 1]",9,15
16,Normal,40,18,"[2, 0, 12]",14,15
17,Normal,40,18,"[2, 1, 10]",13,15
18,Normal,40,18,"[2, 2, 8]",12,15
19,Normal,40,18,"[2, 3, 6]",11,15
20,Normal,40,18,"[2, 4, 4]",10,15
21,Normal,40,18,"[2, 5, 2]",9,15
22,Normal,40,18,"[2, 6, 0]",8,15
23,Normal,40,18,"[3, 0, 9]",12,15
24,Normal,40,18,"[3, 1, 7]",11,15
25,Normal,40,18,"[3, 2, 5]",10,15
26,Normal,40,18,"[3, 3, 3]",9,15
27,Normal,40,18,"[3, 4, 1]",8,15
28,Normal,40,18,"[4, 0, 6]",10,15
29,Normal,40,18,"[4, 1, 4]",9,15
30,Normal,40,18,"[4, 2, 2]",8,16
31,Normal,40,18,"[4, 3, 0]",7,16
32,Normal,40,18,"[5, 0, 3]",8,15
33,Normal,40,18,"[5, 1, 1]",7,16
34,Normal,40,18,"[6, 0, 0]",6,18
35,Let Them Dream,40,16,"[0, 0, 16]",16,17
36,Let Them Dream,40,15,"[0, 0, 15]",15,18
37,Let Them Dream,40,15,"[0, 1, 13]",14,18
38,Let Them Dream,40,15,"[0, 2, 11]",13,18
39,Let Them Dream,40,15,"[0, 3, 9]",12,18
40,Let Them Dream,40,15,"[0, 4, 7]",11,18
41,Let Them Dream,40,15,"[0, 5, 5]",10,18
42,Let Them Dream,40,15,"[0, 6, 3]",9,18
43,Let Them Dream,40,18,"[1, 0, 15]",16,15
44,Let Them Dream,40,17,"[1, 0, 14]",15,16
45,Let Them Dream,40,16,"[1, 0, 13]",14,17
46,Let Them Dream,40,15,"[1, 0, 12]",13,18
47,Let Them Dream,40,15,"[1, 1, 10]",12,18
48,Let Them Dream,40,15,"[1, 2, 8]",11,18
49,Let Them Dream,40,15,"[1, 3, 6]",10,18

In [3]:
df.describe()

        deck_size  agenda_points  num_agendas  average_accesses
count  992.000000     992.000000   992.000000        992.000000
mean    47.423387      19.572581    12.233871         16.945565
std      4.524870       2.140092     2.820163          1.440043
min     40.000000      15.000000     6.000000         14.000000
25%     44.000000      18.000000    10.000000         16.000000
50%     49.000000      20.000000    12.000000         17.000000
75%     50.000000      21.000000    14.000000         18.000000
max     54.000000      23.000000    19.000000         20.000000

In [10]:
df[(df['agenda_type'] == "Normal") & (df['deck_size'] == 40)].head(50)

,agenda_type,deck_size,agenda_points,agenda_counts,num_agendas,average_accesses
0,Normal,40,18,"[0, 2, 14]",16,15
1,Normal,40,18,"[0, 3, 12]",15,15
2,Normal,40,18,"[0, 4, 10]",14,15
3,Normal,40,18,"[0, 5, 8]",13,15
4,Normal,40,18,"[0, 6, 6]",12,15
5,Normal,40,18,"[0, 7, 4]",11,15
6,Normal,40,18,"[0, 8, 2]",10,15
7,Normal,40,18,"[0, 9, 0]",9,16
8,Normal,40,18,"[1, 0, 15]",16,15
9,Normal,40,18,"[1, 1, 13]",15,15
10,Normal,40,18,"[1, 2, 11]",14,15
11,Normal,40,18,"[1, 3, 9]",13,15
12,Normal,40,18,"[1, 4, 7]",12,15
13,Normal,40,18,"[1, 5, 5]",11,15
14,Normal,40,18,"[1, 6, 3]",10,15
15,Normal,40,18,"[1, 7, 1]",9,15
16,Normal,40,18,"[2, 0, 12]",14,15
17,Normal,40,18,"[2, 1, 10]",13,15
18,Normal,40,18,"[2, 2, 8]",12,15
19,Normal,40,18,"[2, 3, 6]",11,15
20,Normal,40,18,"[2, 4, 4]",10,15
21,Normal,40,18,"[2, 5, 2]",9,15
22,Normal,40,18,"[2, 6, 0]",8,15
23,Normal,40,18,"[3, 0, 9]",12,15
24,Normal,40,18,"[3, 1, 7]",11,15
25,Normal,40,18,"[3, 2, 5]",10,15
26,Normal,40,18,"[3, 3, 3]",9,15
27,Normal,40,18,"[3, 4, 1]",8,15
28,Normal,40,18,"[4, 0, 6]",10,15
29,Normal,40,18,"[4, 1, 4]",9,15
30,Normal,40,18,"[4, 2, 2]",8,16
31,Normal,40,18,"[4, 3, 0]",7,16
32,Normal,40,18,"[5, 0, 3]",8,15
33,Normal,40,18,"[5, 1, 1]",7,16
34,Normal,40,18,"[6, 0, 0]",6,18
70,Normal,40,19,"[0, 2, 15]",17,14
71,Normal,40,19,"[0, 3, 13]",16,14
72,Normal,40,19,"[0, 4, 11]",15,14
73,Normal,40,19,"[0, 5, 9]",14,15
74,Normal,40,19,"[0, 6, 7]",13,15
75,Normal,40,19,"[0, 7, 5]",12,15
76,Normal,40,19,"[0, 8, 3]",11,15
77,Normal,40,19,"[0, 9, 1]",10,15
78,Normal,40,19,"[1, 1, 14]",16,14
79,Normal,40,19,"[1, 2, 12]",15,15
80,Normal,40,19,"[1, 3, 10]",14,15
81,Normal,40,19,"[1, 4, 8]",13,15
82,Normal,40,19,"[1, 5, 6]",12,15
83,Normal,40,19,"[1, 6, 4]",11,15
84,Normal,40,19,"[1, 7, 2]",10,15

In [11]:
df[(df['agenda_type'] == "Normal") & (df['deck_size'] == 40) & (df['average_accesses'] != 15)].head(50)

,agenda_type,deck_size,agenda_points,agenda_counts,num_agendas,average_accesses
7,Normal,40,18,"[0, 9, 0]",9,16
30,Normal,40,18,"[4, 2, 2]",8,16
31,Normal,40,18,"[4, 3, 0]",7,16
33,Normal,40,18,"[5, 1, 1]",7,16
34,Normal,40,18,"[6, 0, 0]",6,18
70,Normal,40,19,"[0, 2, 15]",17,14
71,Normal,40,19,"[0, 3, 13]",16,14
72,Normal,40,19,"[0, 4, 11]",15,14
78,Normal,40,19,"[1, 1, 14]",16,14
98,Normal,40,19,"[3, 5, 0]",8,14